---
  - name: sysctl tuning for Debian OS family
    sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      reload: yes
    with_items:
      - { name: net.ipv6.conf.all.disable_ipv6, value: 1 }
      - { name: net.ipv6.conf.default.disable_ipv6, value: 1 }
      - { name: net.ipv4.tcp_tw_recycle, value: 1 }
      - { name: net.ipv4.tcp_tw_reuse, value: 1 }
      - { name: net.ipv4.tcp_fin_timeout, value: 2 }
      - { name: net.ipv4.tcp_keepalive_time, value: 65 }
      - { name: net.core.somaxconn, value: 65535 }
      - { name: net.ipv4.tcp_max_syn_backlog, value: 65535 }
      - { name: net.core.rmem_max, value: 16777216 }
      - { name: net.core.wmem_max, value: 16777216 }
      - { name: vm.swappiness, value: 10 }
    when: ansible_os_family == 'Debian'

  - name: Commit tuning of sysctl
    shell: 'if etckeeper unclean; then etckeeper commit -m "[Ansible] sysctl設定"; fi'
    when: ansible_os_family == 'Debian'

