---
- name: Install libselinux-python
  yum:
    name: libselinux-python
    state: present
  when: ansible_os_family == 'RedHat'

- name: Disable SELinux permanently
  selinux:
    state: disabled
  when: ansible_os_family == 'RedHat'

- shell: 'if etckeeper unclean; then etckeeper commit -m "Ansible - Disable SELinux"; fi'
