---
  - name: Install dependency for RedHat OS family
    yum:
      state: latest
      name: '{{ item }}'
    with_items:
      - "@Development tools"
      - readline-devel
      - jemalloc-devel
    when: ansible_os_family == 'RedHat'

  - name: Install dependency for Debian OS family
    yum:
      state: latest
      name: '{{ item }}'
    with_items:
      - build-essential
    when: ansible_os_family == 'Debian'

  - name: Install systemd file
    copy:
      src: isucon_systemd
      dest: /home/isucon/isucon_systemd
      owner: isucon
      group: isucon
      mode: 0666

  - name: Install puma.rb
    copy:
      src: puma.rb
      dest: /home/isucon/puma.rb
      owner: isucon
      group: isucon
      mode: 0666

  - name: Install rbenv
    git:
      repo: '{{ item.repo }}'
      dest: '{{ item.dest }}'
    with_items:
      - { repo: 'https://github.com/sstephenson/rbenv.git', dest: '/home/{{ ansible_user }}/.rbenv' }
      - { repo: 'https://github.com/sstephenson/ruby-build.git', dest: '/home/{{ ansible_user }}/.rbenv/plugins/ruby-build' }

  - name: Change owner of .rbenv
    file:
      path: '{{ item }}'
      owner: '{{ ansible_user }}'
    with_items:
      - '/home/{{ ansible_user }}/.rbenv'

  - name: Add rbenv definition to .bashrc
    lineinfile:
      state: present
      path: '/home/{{ ansible_user }}/.bashrc'
      insertafter: EOF
      line: '{{ item }}'
    with_items:
      - 'export PATH="$HOME/.rbenv/bin:$PATH"'
      - 'eval "$(rbenv init -)"'

  - name: rubyのインストール
    shell: bash -lc "CONFIGURE_OPTS="--disable-install-rdoc --with-jemalloc" ~/.rbenv/bin/rbenv install -s 2.5.1"
    become: false

  - name: ruby global
    shell: bash -lc "~/.rbenv/bin/rbenv global 2.5.1"
    become: false

  - name: gem アップグレード
    shell: bash -lc "~/.rbenv/versions/2.5.1/bin/gem update --system"
    become: false